// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> en = {
  "logIn": "Log in",
  "enterYourPhoneNumberToLoginViaSms": "Enter your phone number to login via SMS",
  "enterYourPhone": "Enter your phone",
  "numbersAreRequired": "Numbers are required",
  "enterThePinYouHaveGottenViaSms": "Enter the pin you have gotten via SMS",
  "attempts": "Attempts: {}",
  "resendPin": "Resend pin",
  "ifYouDidntReceiveOne": " if you didn't receive one",
  "wrongPhoneNumber": "Wrong phone number? ",
  "goBack": "Go back",
  "loading": "Loading...",
  "movies": "Movies",
  "myTickets": "My tickets",
  "settings": "Settings",
  "noTickets": "No tickets",
  "youCanBuyThemInTheMoviesTab": "You can buy them in the Movies tab",
  "notificationsAndSounds": "Notifications and sounds",
  "privacyAndSecurity": "Privacy and security",
  "switchLanguage": "Switch language",
  "logout": "Logout",
  "byDays": "By days",
  "topCharts": "Top charts",
  "writeYourAnonymousComment": "Write your anonymous comment",
  "submit": "Submit",
  "commentsSection": "Comments section",
  "noCommentsBeTheFirstOne": "No comments? Be the first one!",
  "anonymous": "Anonymous",
  "me": "(Me)",
  "lightMode": "Light Mode",
  "iWouldLikeToWatchInCinemaHouse": "I would like to watch {} in Cinema House",
  "originalName": "Original name: {}",
  "language": "Language: {}",
  "genres": "Genres: {}",
  "country": "Country: {}",
  "director": "Director: {}",
  "durationMinutes": "Duration: {} minutes",
  "recommendedAge": "Recommended age: {}",
  "mainRoles": "Main roles: {}",
  "studio": "Studio: {}",
  "releaseYear": "Release year: {}",
  "trailerOnYoutube": "Trailer on YouTube",
  "plot": "Plot: {}",
  "noInternetConnection": "No internet connection",
  "sessionsSection": "Sessions section",
  "room": "Room: \"{}\"",
  "type": "Type: {}",
  "minimumPrice": "Minimum price: {} UAH",
  "someoneElseHasJustBookedTheSeats": "Someone else has just booked the seats",
  "totalPrice": "Total price: {} UAH",
  "chooseSomeSeatsAbove": "Choose some seats above!",
  "pickedSeats": "Picked seats:",
  "payViaTheCard": "Pay via the card",
  "yourEmail": "Your email",
  "cardNumber": "Card number",
  "theTransactionIsDone": "The transaction is done. Check the \"My ticket\" tab",
  "someErrorOccurred": "Some error occurred",
  "uahToBePayed": "{} UAH to be payed",
  "thisFieldIsRequired": "This field is required",
  "thatsIncorrectEmail": "That's incorrect email",
  "incorrectCardNumber": "Incorrect card number",
  "cardHasExpired": "Card has expired",
  "expiryYearIsInvalid": "Expiry year is invalid",
  "expiryMonthIsInvalid": "Expiry month is invalid",
  "incorrectCvvLength": "Incorrect CVV length",
  "roomRowSeat": "Room: {} + Row: {} + Seat: {}",
  "today": "Today, {}",
  "tomorrow": "tomorrow, {}",
  "rowSeat": "Row: {} + Seat: {}"
};
static const Map<String,dynamic> uk = {
  "logIn": "Увійти",
  "enterYourPhoneNumberToLoginViaSms": "Введіть свій номер телефону, аби увійти через СМС",
  "enterYourPhone": "Введіть ваш номер",
  "numbersAreRequired": "Потребуються цифри",
  "enterThePinYouHaveGottenViaSms": "Введіть пін-код отриманий через СМС",
  "attempts": "Спроби: {}",
  "resendPin": "Переслати пін",
  "ifYouDidntReceiveOne": " якщо не був отриманим",
  "wrongPhoneNumber": "Неправильний номер телефону? ",
  "goBack": "Повернутися",
  "loading": "Завантаження...",
  "movies": "Кіно",
  "myTickets": "Мої білети",
  "settings": "Налаштування",
  "noTickets": "Немає білетів",
  "youCanBuyThemInTheMoviesTab": "Ви можите купити їх у вкладці Кіно",
  "notificationsAndSounds": "Повідомлення та звуки",
  "privacyAndSecurity": "Приватність та безпека",
  "switchLanguage": "Змінити мову",
  "logout": "Вийти з аккаунта",
  "byDays": "За днями",
  "topCharts": "Популярне",
  "writeYourAnonymousComment": "Напишіть свій анонімний коментар",
  "submit": "Підтвердити",
  "commentsSection": "Секція коментарів",
  "noCommentsBeTheFirstOne": "Нема коментарів? Будь першим!",
  "anonymous": "Анонім",
  "me": "(Я)",
  "lightMode": "Світлий режим",
  "iWouldLikeToWatchInCinemaHouse": "Я б хотів подивитися {} в Cinema House",
  "originalName": "Оригінальна назва: {}",
  "language": "Мова: {}",
  "genres": "Жанри: {}",
  "country": "Країна: {}",
  "director": "Режисер: {}",
  "durationMinutes": "Тривалість: {} хвилин",
  "recommendedAge": "Рекомендований вік: {}",
  "mainRoles": "Головні ролі: {}",
  "studio": "Студія: {}",
  "releaseYear": "Рік випуску: {}",
  "trailerOnYoutube": "Трейлер на ютуб",
  "plot": "Сюжет: {}",
  "noInternetConnection": "Немає інтернет з'єднання",
  "sessionsSection": "Секція сесій",
  "room": "Кімната: \"{}\"",
  "type": "Тип: {}",
  "minimumPrice": "Мінімальна ціна: {} ГРН",
  "someoneElseHasJustBookedTheSeats": "Хтось інший щойно забронював ці місця",
  "totalPrice": "Загальна сума: {} ГРН",
  "chooseSomeSeatsAbove": "Виберіть місця!",
  "pickedSeats": "Вибрані місця:",
  "payViaTheCard": "Заплатити цією картою",
  "yourEmail": "Ваша електрона пошта",
  "cardNumber": "Номер карти",
  "theTransactionIsDone": "Транзакція пройшла успішно. Перевірте вкладку \"Мої білети\"",
  "someErrorOccurred": "Виникла якась помилка",
  "uahToBePayed": "{} грн до сплати",
  "thisFieldIsRequired": "Заповніть це поле",
  "thatsIncorrectEmail": "Неправильна електрона пошта",
  "incorrectCardNumber": "Неправильний номер картки",
  "cardHasExpired": "Термін дії картки закінчився",
  "expiryYearIsInvalid": "Рік закінчення недійсний",
  "expiryMonthIsInvalid": "Місяць закінчення недійсний",
  "incorrectCvvLength": "Неправильна довжина CVV",
  "roomRowSeat": "Кімната: {} + ряд: {} + місце: {}",
  "today": "Сьогодні, {}",
  "tomorrow": "Завтра, {}",
  "rowSeat": "Ряд: {} + Місце: {}"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": en, "uk": uk};
}
